# Generated by Django 3.0.8 on 2020-07-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=150)),
                ('dis_info', models.TextField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
