# Generated by Django 3.0.8 on 2020-07-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='title',
        ),
    ]
