# Generated by Django 3.0.8 on 2020-07-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('std_cls', models.CharField(max_length=100)),
                ('std_roll', models.IntegerField()),
            ],
        ),
    ]
